# Generated by Django 4.2.2 on 2023-06-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='library_details',
        ),
    ]
