# Generated by Django 4.2.2 on 2023-06-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
